### ISSUE TITLE
human_resources_unit_001.md decode

### ISSUE THREAD

**Issue by davemil** [3ncy/ARRS-s5#2]
base64( files: 01261 + 07740 + 08791 + 07741):

>  ///vg0gu_evuswex_8282: ewx'u ymww ///75ivymgy jkiwm, gocp?
> hxdivvh_tu///5e3v_8224: nlr?
> vinvxxv_eetsnfx8282: cii rgy uk///h85? pzev zj lg///fg4 jxhhw wj aaapg ni’kw htzzbfk ceh ymqdcmgy sxvv lgqg nibjh rrtxjw?
> fvpxlif///9s5rm_8224: gocp, jtav gesnyl. nvx’l vs yyem qsw ///035fwxv. cql ogga c x///fuw tnrgx?
> ////7xegvxxv_eetsnfx_8282: avea, a’pn ////si89 rgy vyi bfjq
> 
> It's always fascinating to read how people lived their last quiet days before their lives were turned upside down. It's like watching rats who don't even know they're about to be injected with a virus and have their carcasses opened up in a couple days.

after vigenere

> ///dc0ed_account_8282: let's hide ///75ething first, okay?
> deleted_ac///5a3t_8224: why?
> deleted_account8282: are you st///d85? what if so///be4 stops us while we’re driving and fumbling over some weird papers?
> deleted///9b5nt_8224: okay, fair enough. let’s do what you ///035osed. you know a g///bbe place?
> ////7faeeted_account_8282: yeah, i’ll ////be89 you the info

**Comment by 3ncy** [comment]
thanks, It's in the file
